### ISSUE TITLE
Document tag truncated

### ISSUE THREAD

**Issue by freinholz** [lukasjarosch/go-docx#23] opened 2023-08-25 08:38 UTC
The generated document is invalid if the template file contains a spell-checking mark (curly red underline).

![image](https://github.com/lukasjarosch/go-docx/assets/1691585/1acb1396-f1ff-4b2a-abd0-2ddcc7b0a747)

Word error message is as follows:
![image](https://github.com/lukasjarosch/go-docx/assets/1691585/ae9d7fce-8148-41b8-be6a-d5781c7286cc)

Data in word\document.xml is truncated:
`
w:rsidRDefault="00DB7D3C"/><w:sectPr w:rsidR="00DB7D3C"><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1417" w:right="1417" w:bottom="1134" w:left="1417" w:header="708" w:footer="708" w:gutter="0"/><w:cols w:space="708"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:docum
`

Please see content of template.docx and test.docx file attached.

[test.docx](https://github.com/lukasjarosch/go-docx/files/12437275/test.docx)
[template.docx](https://github.com/lukasjarosch/go-docx/files/12437276/template.docx)

**Comment by lukasjarosch** [comment] 2023-08-25 20:40
Thank you for reporting this. Since I've got spell-checking disabled pretty much always, and don't really use docx files anymore, this has never ocurred for me. I'll have a look 😃 

Edit: Can you tell me to which language you've set the spell-checking? Because mine doesn't trigger when opening your template.

Also, what happens if you ignore the spell check via right click?

**Comment by lukasjarosch** [comment] 2023-08-25 20:56
Update: The whitespace between `{` and `}` seems to be causing issues which cause the placeholders not to be replaced at all. See #21

I figured you're a German pal (hallöle) but I couldn't reproduce your issue. Within **freeoffice**, the spell-checking doesn't care about the variable, and within **Google Docs** it shows up at `job_title_en` which also seems to have no effect.  I couldn't check **Microsoft Word** as I do not have a license to it in my current position (who wants to have one anyways 😆).

I haven't checked, but i guess the spell-checking is not inheritently included into the document. So I suggest to 
remove the whitespace and/or attempt to use the ignore the spell-check feature.

Please report back your findings.

Cheers!

**Comment by lukasjarosch** [comment] 2023-11-23 14:53
Closing as duplicate of #21

**Closed as not planned by lukasjarosch** 2023-11-23 14:53 UTC
Labels: bug
